site_name: relrod life notes
theme:
  name: material
plugins:
  - search
  - awesome-pages
  - table-reader
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
